language: java
sudo: required

jdk:
  - openjdk8
  - oraclejdk8

dist: trusty

install:
  - curl https://raw.githubusercontent.com/italiangrid/build-settings/master/maven/cnaf-mirror-settings.xml -o $HOME/.m2/settings.xml

cache:
  directories:
  - "$HOME/.m2/repository"
