language: java

jdk:
  - openjdk8
  - oraclejdk8
dist: trusty

script:
  - curl https://raw.githubusercontent.com/italiangrid/build-settings/master/maven/cnaf-mirror-settings.xml -o $HOME/.m2/settings.xml
  - mvn -U -B clean install 

cache:
  directories:
  - "$HOME/.m2/repository"
